{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9bc78bf4-3bdb-4d56-9aef-50202733b8c1",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-05-16 20:42:34,173 (__init__.py:1212 MainThread) ERROR - TeleBot: \"Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\"\n",
      "2024-05-16 20:42:34,177 (__init__.py:1214 MainThread) ERROR - TeleBot: \"Exception traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\__init__.py\", line 1205, in __threaded_polling\n",
      "    polling_thread.raise_exceptions()\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\util.py\", line 111, in raise_exceptions\n",
      "    raise self.exception_info\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\util.py\", line 93, in run\n",
      "    task(*args, **kwargs)\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\__init__.py\", line 675, in __retrieve_updates\n",
      "    updates = self.get_updates(offset=(self.last_update_id + 1),\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\__init__.py\", line 647, in get_updates\n",
      "    json_updates = apihelper.get_updates(\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\apihelper.py\", line 327, in get_updates\n",
      "    return _make_request(token, method_url, params=payload)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\apihelper.py\", line 167, in _make_request\n",
      "    json_result = _check_result(method_name, result)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\apihelper.py\", line 194, in _check_result\n",
      "    raise ApiTelegramException(method_name, result, result_json)\n",
      "telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "\"\n",
      "2024-05-16 20:42:37,067 (__init__.py:1212 MainThread) ERROR - TeleBot: \"Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: message text is empty\"\n",
      "2024-05-16 20:42:37,068 (__init__.py:1214 MainThread) ERROR - TeleBot: \"Exception traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\__init__.py\", line 1206, in __threaded_polling\n",
      "    self.worker_pool.raise_exceptions()\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\util.py\", line 150, in raise_exceptions\n",
      "    raise self.exception_info\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\util.py\", line 93, in run\n",
      "    task(*args, **kwargs)\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Temp\\ipykernel_20540\\2304273984.py\", line 27, in take_language\n",
      "    choose_domain(message)\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Temp\\ipykernel_20540\\2304273984.py\", line 41, in choose_domain\n",
      "    glottobot.send_message(chat_id, '',\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\__init__.py\", line 1742, in send_message\n",
      "    apihelper.send_message(\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\apihelper.py\", line 270, in send_message\n",
      "    return _make_request(token, method_url, params=payload, method='post')\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\apihelper.py\", line 167, in _make_request\n",
      "    json_result = _check_result(method_name, result)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\apihelper.py\", line 194, in _check_result\n",
      "    raise ApiTelegramException(method_name, result, result_json)\n",
      "telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: message text is empty\n",
      "\"\n",
      "2024-05-16 20:43:04,650 (__init__.py:1212 MainThread) ERROR - TeleBot: \"Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\"\n",
      "2024-05-16 20:43:04,652 (__init__.py:1214 MainThread) ERROR - TeleBot: \"Exception traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\__init__.py\", line 1205, in __threaded_polling\n",
      "    polling_thread.raise_exceptions()\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\util.py\", line 111, in raise_exceptions\n",
      "    raise self.exception_info\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\util.py\", line 93, in run\n",
      "    task(*args, **kwargs)\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\__init__.py\", line 675, in __retrieve_updates\n",
      "    updates = self.get_updates(offset=(self.last_update_id + 1),\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\__init__.py\", line 647, in get_updates\n",
      "    json_updates = apihelper.get_updates(\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\apihelper.py\", line 327, in get_updates\n",
      "    return _make_request(token, method_url, params=payload)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\apihelper.py\", line 167, in _make_request\n",
      "    json_result = _check_result(method_name, result)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\apihelper.py\", line 194, in _check_result\n",
      "    raise ApiTelegramException(method_name, result, result_json)\n",
      "telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "\"\n",
      "2024-05-16 20:43:40,026 (__init__.py:1212 MainThread) ERROR - TeleBot: \"Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\"\n",
      "2024-05-16 20:43:40,030 (__init__.py:1214 MainThread) ERROR - TeleBot: \"Exception traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\__init__.py\", line 1205, in __threaded_polling\n",
      "    polling_thread.raise_exceptions()\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\util.py\", line 111, in raise_exceptions\n",
      "    raise self.exception_info\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\util.py\", line 93, in run\n",
      "    task(*args, **kwargs)\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\__init__.py\", line 675, in __retrieve_updates\n",
      "    updates = self.get_updates(offset=(self.last_update_id + 1),\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\__init__.py\", line 647, in get_updates\n",
      "    json_updates = apihelper.get_updates(\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\apihelper.py\", line 327, in get_updates\n",
      "    return _make_request(token, method_url, params=payload)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\apihelper.py\", line 167, in _make_request\n",
      "    json_result = _check_result(method_name, result)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\apihelper.py\", line 194, in _check_result\n",
      "    raise ApiTelegramException(method_name, result, result_json)\n",
      "telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "\"\n",
      "2024-05-16 20:43:47,308 (__init__.py:1086 MainThread) ERROR - TeleBot: \"Infinity polling exception: Language.phoible_extract() takes 1 positional argument but 2 were given\"\n",
      "2024-05-16 20:43:47,309 (__init__.py:1088 MainThread) ERROR - TeleBot: \"Exception traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\__init__.py\", line 1081, in infinity_polling\n",
      "    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\__init__.py\", line 1169, in polling\n",
      "    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\__init__.py\", line 1244, in __threaded_polling\n",
      "    raise e\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\__init__.py\", line 1206, in __threaded_polling\n",
      "    self.worker_pool.raise_exceptions()\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\util.py\", line 150, in raise_exceptions\n",
      "    raise self.exception_info\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\util.py\", line 93, in run\n",
      "    task(*args, **kwargs)\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\__init__.py\", line 8404, in _run_middlewares_and_handler\n",
      "    result = handler['function'](message)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Temp\\ipykernel_20540\\2304273984.py\", line 50, in phonetics\n",
      "    glottobot.send_message(chat_id, f'PHOIBLE data: \\n\\n{language.phoible_extract(\"phonetics\")}')\n",
      "                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "TypeError: Language.phoible_extract() takes 1 positional argument but 2 were given\n",
      "\"\n",
      "2024-05-16 20:43:53,910 (__init__.py:1212 MainThread) ERROR - TeleBot: \"Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: message text is empty\"\n",
      "2024-05-16 20:43:53,912 (__init__.py:1214 MainThread) ERROR - TeleBot: \"Exception traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\__init__.py\", line 1206, in __threaded_polling\n",
      "    self.worker_pool.raise_exceptions()\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\util.py\", line 150, in raise_exceptions\n",
      "    raise self.exception_info\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\util.py\", line 93, in run\n",
      "    task(*args, **kwargs)\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\__init__.py\", line 8404, in _run_middlewares_and_handler\n",
      "    result = handler['function'](message)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Temp\\ipykernel_20540\\2304273984.py\", line 27, in take_language\n",
      "    choose_domain(message)\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Temp\\ipykernel_20540\\2304273984.py\", line 41, in choose_domain\n",
      "    glottobot.send_message(chat_id, '',\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\__init__.py\", line 1742, in send_message\n",
      "    apihelper.send_message(\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\apihelper.py\", line 270, in send_message\n",
      "    return _make_request(token, method_url, params=payload, method='post')\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\apihelper.py\", line 167, in _make_request\n",
      "    json_result = _check_result(method_name, result)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\apihelper.py\", line 194, in _check_result\n",
      "    raise ApiTelegramException(method_name, result, result_json)\n",
      "telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: message text is empty\n",
      "\"\n",
      "2024-05-16 20:43:59,681 (__init__.py:1212 MainThread) ERROR - TeleBot: \"Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: message text is empty\"\n",
      "2024-05-16 20:43:59,684 (__init__.py:1214 MainThread) ERROR - TeleBot: \"Exception traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\__init__.py\", line 1206, in __threaded_polling\n",
      "    self.worker_pool.raise_exceptions()\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\util.py\", line 150, in raise_exceptions\n",
      "    raise self.exception_info\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\util.py\", line 93, in run\n",
      "    task(*args, **kwargs)\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\__init__.py\", line 8404, in _run_middlewares_and_handler\n",
      "    result = handler['function'](message)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Temp\\ipykernel_20540\\2304273984.py\", line 27, in take_language\n",
      "    choose_domain(message)\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Temp\\ipykernel_20540\\2304273984.py\", line 41, in choose_domain\n",
      "    glottobot.send_message(chat_id, '',\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\__init__.py\", line 1742, in send_message\n",
      "    apihelper.send_message(\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\apihelper.py\", line 270, in send_message\n",
      "    return _make_request(token, method_url, params=payload, method='post')\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\apihelper.py\", line 167, in _make_request\n",
      "    json_result = _check_result(method_name, result)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\apihelper.py\", line 194, in _check_result\n",
      "    raise ApiTelegramException(method_name, result, result_json)\n",
      "telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: message text is empty\n",
      "\"\n",
      "2024-05-16 20:44:06,873 (__init__.py:1212 MainThread) ERROR - TeleBot: \"Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: message text is empty\"\n",
      "2024-05-16 20:44:06,876 (__init__.py:1214 MainThread) ERROR - TeleBot: \"Exception traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\__init__.py\", line 1206, in __threaded_polling\n",
      "    self.worker_pool.raise_exceptions()\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\util.py\", line 150, in raise_exceptions\n",
      "    raise self.exception_info\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\util.py\", line 93, in run\n",
      "    task(*args, **kwargs)\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\__init__.py\", line 8404, in _run_middlewares_and_handler\n",
      "    result = handler['function'](message)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Temp\\ipykernel_20540\\2304273984.py\", line 27, in take_language\n",
      "    choose_domain(message)\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Temp\\ipykernel_20540\\2304273984.py\", line 41, in choose_domain\n",
      "    glottobot.send_message(chat_id, '',\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\__init__.py\", line 1742, in send_message\n",
      "    apihelper.send_message(\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\apihelper.py\", line 270, in send_message\n",
      "    return _make_request(token, method_url, params=payload, method='post')\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\apihelper.py\", line 167, in _make_request\n",
      "    json_result = _check_result(method_name, result)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\apihelper.py\", line 194, in _check_result\n",
      "    raise ApiTelegramException(method_name, result, result_json)\n",
      "telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: message text is empty\n",
      "\"\n",
      "2024-05-16 20:44:43,395 (__init__.py:1212 MainThread) ERROR - TeleBot: \"Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\"\n",
      "2024-05-16 20:44:43,397 (__init__.py:1214 MainThread) ERROR - TeleBot: \"Exception traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\__init__.py\", line 1205, in __threaded_polling\n",
      "    polling_thread.raise_exceptions()\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\util.py\", line 111, in raise_exceptions\n",
      "    raise self.exception_info\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\util.py\", line 93, in run\n",
      "    task(*args, **kwargs)\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\__init__.py\", line 675, in __retrieve_updates\n",
      "    updates = self.get_updates(offset=(self.last_update_id + 1),\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\__init__.py\", line 647, in get_updates\n",
      "    json_updates = apihelper.get_updates(\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\apihelper.py\", line 327, in get_updates\n",
      "    return _make_request(token, method_url, params=payload)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\apihelper.py\", line 167, in _make_request\n",
      "    json_result = _check_result(method_name, result)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\apihelper.py\", line 194, in _check_result\n",
      "    raise ApiTelegramException(method_name, result, result_json)\n",
      "telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "\"\n",
      "2024-05-16 20:45:48,564 (__init__.py:1212 MainThread) ERROR - TeleBot: \"Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\"\n",
      "2024-05-16 20:45:48,567 (__init__.py:1214 MainThread) ERROR - TeleBot: \"Exception traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\__init__.py\", line 1205, in __threaded_polling\n",
      "    polling_thread.raise_exceptions()\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\util.py\", line 111, in raise_exceptions\n",
      "    raise self.exception_info\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\util.py\", line 93, in run\n",
      "    task(*args, **kwargs)\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\__init__.py\", line 675, in __retrieve_updates\n",
      "    updates = self.get_updates(offset=(self.last_update_id + 1),\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\__init__.py\", line 647, in get_updates\n",
      "    json_updates = apihelper.get_updates(\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\apihelper.py\", line 327, in get_updates\n",
      "    return _make_request(token, method_url, params=payload)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\apihelper.py\", line 167, in _make_request\n",
      "    json_result = _check_result(method_name, result)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\apihelper.py\", line 194, in _check_result\n",
      "    raise ApiTelegramException(method_name, result, result_json)\n",
      "telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "\"\n",
      "2024-05-16 20:46:52,219 (__init__.py:1212 MainThread) ERROR - TeleBot: \"Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\"\n",
      "2024-05-16 20:46:52,223 (__init__.py:1214 MainThread) ERROR - TeleBot: \"Exception traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\__init__.py\", line 1205, in __threaded_polling\n",
      "    polling_thread.raise_exceptions()\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\util.py\", line 111, in raise_exceptions\n",
      "    raise self.exception_info\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\util.py\", line 93, in run\n",
      "    task(*args, **kwargs)\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\__init__.py\", line 675, in __retrieve_updates\n",
      "    updates = self.get_updates(offset=(self.last_update_id + 1),\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\__init__.py\", line 647, in get_updates\n",
      "    json_updates = apihelper.get_updates(\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\apihelper.py\", line 327, in get_updates\n",
      "    return _make_request(token, method_url, params=payload)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\apihelper.py\", line 167, in _make_request\n",
      "    json_result = _check_result(method_name, result)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\apihelper.py\", line 194, in _check_result\n",
      "    raise ApiTelegramException(method_name, result, result_json)\n",
      "telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "\"\n",
      "2024-05-16 20:47:55,633 (__init__.py:1212 MainThread) ERROR - TeleBot: \"Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\"\n",
      "2024-05-16 20:47:55,635 (__init__.py:1214 MainThread) ERROR - TeleBot: \"Exception traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\__init__.py\", line 1205, in __threaded_polling\n",
      "    polling_thread.raise_exceptions()\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\util.py\", line 111, in raise_exceptions\n",
      "    raise self.exception_info\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\util.py\", line 93, in run\n",
      "    task(*args, **kwargs)\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\__init__.py\", line 675, in __retrieve_updates\n",
      "    updates = self.get_updates(offset=(self.last_update_id + 1),\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\__init__.py\", line 647, in get_updates\n",
      "    json_updates = apihelper.get_updates(\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\apihelper.py\", line 327, in get_updates\n",
      "    return _make_request(token, method_url, params=payload)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\apihelper.py\", line 167, in _make_request\n",
      "    json_result = _check_result(method_name, result)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\apihelper.py\", line 194, in _check_result\n",
      "    raise ApiTelegramException(method_name, result, result_json)\n",
      "telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "\"\n",
      "2024-05-16 20:49:00,811 (__init__.py:1212 MainThread) ERROR - TeleBot: \"Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\"\n",
      "2024-05-16 20:49:00,812 (__init__.py:1214 MainThread) ERROR - TeleBot: \"Exception traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\__init__.py\", line 1205, in __threaded_polling\n",
      "    polling_thread.raise_exceptions()\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\util.py\", line 111, in raise_exceptions\n",
      "    raise self.exception_info\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\util.py\", line 93, in run\n",
      "    task(*args, **kwargs)\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\__init__.py\", line 675, in __retrieve_updates\n",
      "    updates = self.get_updates(offset=(self.last_update_id + 1),\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\__init__.py\", line 647, in get_updates\n",
      "    json_updates = apihelper.get_updates(\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\apihelper.py\", line 327, in get_updates\n",
      "    return _make_request(token, method_url, params=payload)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\apihelper.py\", line 167, in _make_request\n",
      "    json_result = _check_result(method_name, result)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\mboga\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\telebot\\apihelper.py\", line 194, in _check_result\n",
      "    raise ApiTelegramException(method_name, result, result_json)\n",
      "telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "\"\n"
     ]
    }
   ],
   "source": [
    "import telebot\n",
    "from telebot import types\n",
    "from aiogram.types import (ReplyKeyboardRemove, ReplyKeyboardMarkup, KeyboardButton)\n",
    "\n",
    "glottobot = telebot.TeleBot('6968053374:AAFnvlfo95Bvfn7IzPPSHWI6keFEoFFiiBU')\n",
    "\n",
    "\n",
    "users = {}\n",
    "\n",
    "\n",
    "@glottobot.message_handler(commands=['start'])\n",
    "def send_welcome(message):\n",
    "    glottobot.reply_to(message, \n",
    "                       f'Hi! This is a bot that can help you to get general info about your requested language from typological databases. Bases currently available are WALS, Phoible, Grambank, and Glottolog.\\n\\nSend me a language you want to learn more about:')\n",
    "    glottobot.register_next_step_handler(message, take_language)\n",
    "\n",
    "\n",
    "@glottobot.message_handler(func=lambda message: message.text not in {'phonetics', 'morphology', 'syntax', 'lexicon'})\n",
    "def take_language(message):\n",
    "    language_name = message.text.title()\n",
    "    language = Language(language_name)\n",
    "    chat_id = message.chat.id\n",
    "    users[chat_id] = language\n",
    "    glottobot.send_message(chat_id, \n",
    "                           f'Ваш язык {language.name}? я пока очень тупой бот. Тем не менее выбирай, че ты бы хотел узнать о языке, личинка лингвиста (с)')\n",
    "    if language not in {'not-moksha'}:\n",
    "        choose_domain(message)\n",
    "\n",
    "\n",
    "def choose_domain(message):\n",
    "    chat_id = message.chat.id\n",
    "    keyboard = telebot.types.ReplyKeyboardMarkup(resize_keyboard=True)\n",
    "    button_phonetics = telebot.types.KeyboardButton(text='phonetics')\n",
    "    keyboard.add(button_phonetics)\n",
    "    button_morphology = telebot.types.KeyboardButton(text='morphology')\n",
    "    keyboard.add(button_morphology)\n",
    "    button_syntax = telebot.types.KeyboardButton(text='syntax')\n",
    "    keyboard.add(button_syntax)\n",
    "    button_lexicon = telebot.types.KeyboardButton(text='lexicon')\n",
    "    keyboard.add(button_lexicon)\n",
    "    glottobot.send_message(chat_id, '',\n",
    "                           reply_markup=keyboard)\n",
    "\n",
    "\n",
    "@glottobot.message_handler(func=lambda message: message.text == 'phonetics')\n",
    "def phonetics(message):\n",
    "    chat_id = message.chat.id\n",
    "    language = users[chat_id]\n",
    "    glottobot.send_message(chat_id, f'WALS data: \\n\\n{language.wals_extract(\"phonetics\")}')\n",
    "    glottobot.send_message(chat_id, f'PHOIBLE data: \\n\\n{language.phoible_extract(\"phonetics\")}')\n",
    "    \n",
    "\n",
    "@glottobot.message_handler(func=lambda message: message.text == 'morphology')\n",
    "def morphology(message):\n",
    "    chat_id = message.chat.id\n",
    "    language = users[chat_id]\n",
    "    glottobot.send_message(chat_id, \n",
    "                           f'WALS data: \\n\\n{language.wals_extract(\"morphology\")}')\n",
    "    glottobot.send_message(chat_id, \n",
    "                           f'You can also check out {language.is_data_available} of the {language.name} language. For a new language just type its name')\n",
    "    if glottobot.message_handler == 'choose_language':\n",
    "        glottobot.register_next_step_handler(message, take_language)\n",
    "\n",
    "@glottobot.message_handler(func=lambda message: message.text == 'syntax')\n",
    "def syntax(message):\n",
    "    chat_id = message.chat.id\n",
    "    language = users[message.chat.id]\n",
    "    glottobot.send_message(chat_id, \n",
    "                           f'WALS data: \\n\\n{language.wals_extract(\"syntax\")}')\n",
    "\n",
    "\n",
    "@glottobot.message_handler(func=lambda message: message.text == 'lexicon')\n",
    "def lexicon(message):\n",
    "    chat_id = message.chat.id\n",
    "    language = users[chat_id]\n",
    "    glottobot.send_message(chat_id, \n",
    "                           f'WALS data: \\n\\n{language.wals_extract(\"lexicon\")}')\n",
    "\n",
    "@glottobot.message_handler(commands=['anecdote'])\n",
    "def anecdote(message):\n",
    "    glottobot.reply_to(message, 'When the inventor of the USB died and he was being buried, at first he was ')\n",
    "\n",
    "class Language:\n",
    "\n",
    "    def __init__(self, name):\n",
    "        self.name = name\n",
    "\n",
    "    def is_data_available(self):\n",
    "        pass\n",
    "\n",
    "    def phoible_extract(self):\n",
    "        pass\n",
    "\n",
    "    def wals_extract(self, user_field):\n",
    "        pass\n",
    "\n",
    "    def grambank_extract(self):\n",
    "        pass\n",
    "\n",
    "    def glottolog_extract(self):\n",
    "        pass\n",
    "    \n",
    "\n",
    "if __name__ == '__main__':\n",
    "    glottobot.infinity_polling()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "488a0066-bebc-41ea-b0f8-bf0dd502ae29",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
